-- Drops the storefront columns from reunion_events: external_shop_url, shop_products, shop_active.
--
-- Generated by drizzle-kit and correct as generated — three independent column drops with no ordering
-- hazard, unlike 0011. IF EXISTS added only so the file is safe to re-run.
--
-- THIS DESTROYS DATA, though not much: external_shop_url is a link an organiser typed into
-- /admin/storefront, and shop_products is the JSONB list of shirts shown on /shop. Both are content
-- rather than records — nothing was ever sold through this app, so no order or payment depends on them.
-- Worth copying the URL out first if it points somewhere real:
--   SELECT year, external_shop_url FROM reunion_events WHERE external_shop_url IS NOT NULL;

ALTER TABLE "reunion_events" DROP COLUMN IF EXISTS "external_shop_url";--> statement-breakpoint
ALTER TABLE "reunion_events" DROP COLUMN IF EXISTS "shop_products";--> statement-breakpoint
ALTER TABLE "reunion_events" DROP COLUMN IF EXISTS "shop_active";
